// Shared snarkjs→BN254 byte helpers for Node scripts. Mirrors
// src/lib/zk/groth16-serialize.ts; both are pinned to the same contract golden
// vectors (the contract fixture was generated by this exact logic).
//
// Intentional duplication: TS cannot be imported by .mjs scripts directly.
//
// BN254 serialization (from soroban-sdk 25.3.1 src/crypto/bn254.rs):
//   Bn254Fp       : 32-byte big-endian field element.
//   Bn254G1Affine : be32(X) || be32(Y)                              (64 bytes)
//   Bn254G2Affine : Fp2 = be32(c1) || be32(c0)  [imaginary FIRST];
//                   point = be32(X.c1)||be32(X.c0)||be32(Y.c1)||be32(Y.c0) (128 bytes)
//   Fr / signal   : 32-byte big-endian.
// snarkjs JSON stores G2 coords as [c0, c1] pairs, so each pair is SWAPPED here.

/** decimal string -> 32-byte big-endian Uint8Array (one BN254 Fp element). */
export function fpToBe32(decimal) {
  let v = BigInt(decimal);
  if (v < 0n) throw new Error(`negative field element: ${decimal}`);
  const out = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) { out[i] = Number(v & 0xffn); v >>= 8n; }
  if (v !== 0n) throw new Error(`field element too large: ${decimal}`);
  return out;
}

function concat(...a) {
  const out = new Uint8Array(a.reduce((n, x) => n + x.length, 0));
  let o = 0; for (const x of a) { out.set(x, o); o += x.length; } return out;
}

/** n -> 4-byte big-endian Uint8Array (u32). */
export function u32Be(n) {
  return new Uint8Array([(n >>> 24) & 0xff, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff]);
}

/** G1 affine [x, y, "1"] (snarkjs) -> 64 bytes be32(x)||be32(y). */
export function g1ToBytes([x, y]) { return concat(fpToBe32(x), fpToBe32(y)); }

/**
 * G2 affine [[x0, x1], [y0, y1], ["1","0"]] (snarkjs) ->
 * 128 bytes be32(x1)||be32(x0)||be32(y1)||be32(y0)  (imaginary c1 FIRST).
 */
export function g2ToBytes([[x0, x1], [y0, y1]]) {
  return concat(fpToBe32(x1), fpToBe32(x0), fpToBe32(y1), fpToBe32(y0));
}

/**
 * Serialize a snarkjs verification key into the contract's VerificationKey::to_bytes layout:
 *   alpha(G1) | beta(G2) | gamma(G2) | delta(G2) | ic_len(u32 BE) | ic[*](G1)
 */
export function serializeVerificationKey(vk) {
  return concat(
    g1ToBytes(vk.vk_alpha_1), g2ToBytes(vk.vk_beta_2), g2ToBytes(vk.vk_gamma_2),
    g2ToBytes(vk.vk_delta_2), u32Be(vk.IC.length), ...vk.IC.map(g1ToBytes),
  );
}

/** Uint8Array -> lowercase hex string. */
export function toHex(bytes) {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}
